package com.example.practica4.status;

public enum Materias {
	LENGUA, MATEMATICA, IDIOMAS, ED_FISICA, CS_SOCIALES, CS_NATURALES,
	FISICA, QUIMICA, TALLER, HISTORIA, GEOGRAFIA, ARTE, TECNOLOGIA,
	INFORMATICA;
}
